{
 "title": "Cooling",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "FAN1 RPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sensor_fan1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FAN2 RPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "sensor_fan2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FAN3 RPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "sensor_fan3", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FAN4 RPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    { "expr": "sensor_fan4", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FAN5 RPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    { "expr": "sensor_fan5", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FAN6 RPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    { "expr": "sensor_fan6", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FAN7 RPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "targets": [
    { "expr": "sensor_fan7", "legendFormat": "__auto" }
   ]
  }
 ]
}