{
 "title": "Power",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU1 Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sensor_vcpu1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU2 Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "sensor_vcpu2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DIM Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "sensor_vdimmab", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "1.5V PCH Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    { "expr": "sensor_1_5v_pch", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "1.05V PCH Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "targets": [
    { "expr": "sensor_1_05v_pch", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "VBAT Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "targets": [
    { "expr": "sensor_vbat", "legendFormat": "__auto" }
   ]
  }
 ]
}