{
 "title": "Thermal",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU 1 Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sensor_cpu1_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU 2 Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 0 },
   "targets": [
    { "expr": "sensor_cpu2_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 0 },
   "targets": [
    { "expr": "sensor_system_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PCH Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "targets": [
    { "expr": "sensor_pch_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peripheral Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 7 },
   "targets": [
    { "expr": "sensor_peripheral_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HDD Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 7 },
   "targets": [
    { "expr": "sensor_hdd_temp", "legendFormat": "__auto" }
   ]
  }
 ]
}